### ISSUE TITLE
Error in Windows

### ISSUE THREAD

**Issue by caperucitaferoz** [jonian/script.module.acestream#1]
https://github.com/jonian/script.module.acestream/blob/fb8f109d46613d8e9a7cfb02396179eaca6be291/lib/acestream/engine.py#L48
os.setsid fails in windows. 
I propose:

```
try:
    kwargs['preexec_fn'] = os.setsid
except: 
    kwargs['creationflags']= 
            subprocess.CREATE_NEW_PROCESS_GROUP
```

**Comment by jonian** [comment]
Hi @caperucitaferoz, thanks for the report. I don't have access to a windows machine and can't test it. Can you submit a PR for this and any other issues you have on windows?

**Comment by caperucitaferoz** [comment]
ok I'll try

**Comment by caperucitaferoz** [comment]
PR create
